"""Generate the four single-input rotor wrench actuators from one config file."""

import argparse
import csv
import json
import math
import xml.etree.ElementTree as ET
from pathlib import Path

from prepare_mine_uav_visual import ORIGIN_MM


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "models" / "rotor_config.json"
MODEL = ROOT / "models" / "mine_uav_visual.xml"
OUTPUT = ROOT / "models" / "rotor_actuators.xml"
STL_REPORT = ROOT / "reports" / "stl_report.csv"


def read_config(path: Path) -> dict:
    config = json.loads(path.read_text(encoding="utf-8"))
    signs = config["rotation_signs"]
    if len(signs) != 4 or any(type(sign) is not int or sign not in (-1, 1) for sign in signs):
        raise ValueError("rotation_signs must contain four integers, each +1 or -1")
    for key in ("k_f_n_per_rad_s_squared", "k_m_nm_per_rad_s_squared"):
        value = config[key]
        if not isinstance(value, (int, float)) or not math.isfinite(value) or value <= 0:
            raise ValueError(f"{key} must be finite and positive")
    return config


def cad_motor_centers() -> list[tuple[float, float, float]]:
    with STL_REPORT.open(newline="", encoding="utf-8-sig") as stream:
        rows = list(csv.DictReader(stream))
    positions = []
    for i in range(1, 5):
        matches = [row for row in rows if row["filename"].endswith(f"U7-{i}.STL") and row["status"] == "ok"]
        if len(matches) != 1:
            raise ValueError(f"Expected exactly one readable U7-{i}.STL, found {len(matches)}")
        row = matches[0]
        x, y, z = (float(row[f"centroid_{axis}"]) for axis in "xyz")
        positions.append((
            (x - float(ORIGIN_MM[0])) * 0.001,
            -(z - float(ORIGIN_MM[2])) * 0.001,
            (y - float(ORIGIN_MM[1])) * 0.001,
        ))
    return positions


def validate_sites(centers: list[tuple[float, float, float]]) -> None:
    root = ET.parse(MODEL).getroot()
    for i, expected in enumerate(centers, start=1):
        site = root.find(f".//site[@name='motor_{i}_site']")
        if site is None:
            raise ValueError(f"Missing motor_{i}_site in {MODEL}")
        actual = tuple(float(value) for value in site.attrib["pos"].split())
        if len(actual) != 3 or max(abs(a - b) for a, b in zip(actual, expected)) > 1e-6:
            raise ValueError(f"motor_{i}_site {actual} differs from transformed U7 STL centroid {expected}")


def actuator_xml(config: dict) -> str:
    k_f = config["k_f_n_per_rad_s_squared"]
    k_m = config["k_m_nm_per_rad_s_squared"]
    lines = [
        '<mujoco>',
        '  <!-- GENERATED by scripts/build_rotor_model.py from models/rotor_config.json. -->',
        '  <!-- ctrl[i] = omega_i^2 in (rad/s)^2; site gear = [0,0,k_f,0,0,s_i*k_m]. -->',
        '  <actuator>',
    ]
    for i, sign in enumerate(config["rotation_signs"], start=1):
        lines.append(
            f'    <motor name="motor_{i}_wrench" site="motor_{i}_site" '
            f'gear="0 0 {k_f:.17g} 0 0 {sign * k_m:.17g}"/>'
        )
    lines.extend(['  </actuator>', '</mujoco>', ''])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated actuator XML is stale")
    args = parser.parse_args()
    config = read_config(CONFIG)
    centers = cad_motor_centers()
    validate_sites(centers)
    rendered = actuator_xml(config)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("rotor_actuators.xml is stale; run build_rotor_model.py")
    else:
        OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"k_f={config['k_f_n_per_rad_s_squared']:.12g} N/(rad/s)^2")
    print(f"k_m={config['k_m_nm_per_rad_s_squared']:.12g} N*m/(rad/s)^2")
    print(f"rotation_signs={config['rotation_signs']} ({config['note']})")
    for i, center in enumerate(centers, start=1):
        print(f"motor_{i}_site={center} m")
    print(f"{'Checked' if args.check else 'Generated'} {OUTPUT}")


if __name__ == "__main__":
    main()
